#!/bin/bash
sudo apt-get install curl
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sleep 5
sudo npm install -g crunchdown
sleep 1 
mkidr ~/animedownloader
cd ~/animedownloader
wget 